spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ussp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lunan998998

  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 驼峰命名规则和下划线命名自动转化

ai:
  provider:
    endpoint: https://ark.cn-beijing.volces.com/api/v3
    apikey: d36571c5-ec3b-48d6-bbca-df026656d5d3
    model: doubao-seed-1-6-251015